package application

import (
	"fmt"
	"math"
	"strings"
)

// StrengthLevel is a rough, honest classification of how hard a
// machine-generated secret is to brute-force, based on precise entropy.
// Never computed for a human-typed password (spec section 10.7).
type StrengthLevel string

const (
	StrengthLow      StrengthLevel = "low"
	StrengthMedium   StrengthLevel = "medium"
	StrengthHigh     StrengthLevel = "high"
	StrengthVeryHigh StrengthLevel = "very high"
)

// GeneratedStrength is spec section 10.7's strength indicator: a level
// plus a concrete, verifiable reason, not a bare number presented as a
// guarantee.
type GeneratedStrength struct {
	Bits   float64
	Level  StrengthLevel
	Reason string
}

// EstimateGeneratedStrength computes the strength of a secret built from
// unitCount independently, uniformly randomly chosen units, each drawn
// from a fixed space of spaceSize possibilities (spec section 10.7). This
// precise a figure is only honest for something generated uniformly at
// random by this application — GeneratePassword and a future passphrase
// generator both satisfy that. A human-typed password does not, and spec
// section 10.7 explicitly forbids presenting a precise bit count for one.
//
// unitNoun names one unit ("character", "word"); spaceNoun names what they
// are drawn from ("alphabet", "wordlist").
func EstimateGeneratedStrength(unitCount, spaceSize int, unitNoun, spaceNoun string) GeneratedStrength {
	bits := float64(unitCount) * math.Log2(float64(spaceSize))
	reason := fmt.Sprintf(
		"%d independently chosen %s%s from a %d-%s %s.",
		unitCount, unitNoun, pluralSuffix(unitCount), spaceSize, unitNoun, spaceNoun,
	)
	return GeneratedStrength{
		Bits:   bits,
		Level:  strengthLevel(bits),
		Reason: reason,
	}
}

// EstimatePasswordStrength computes strength for a password generated by
// GeneratePassword under policy. The alphabet size is derived from policy
// itself via the same classAlphabets helper GeneratePassword uses, so it
// can never drift out of sync with what was actually drawn from.
func EstimatePasswordStrength(policy PasswordPolicy) GeneratedStrength {
	spaceSize := len(strings.Join(classAlphabets(policy), ""))
	return EstimateGeneratedStrength(policy.Length, spaceSize, "character", "alphabet")
}

// strengthLevel's boundaries are this project's own judgment call — spec
// section 10.7 requires a level and an honest reason but does not mandate
// exact bit thresholds. 75 bits is deliberately chosen so a 6-word
// passphrase (~77.5 bits, spec section 7.4's table) lands in "high" rather
// than "medium", matching spec section 7.3 calling 6 words "strong".
func strengthLevel(bits float64) StrengthLevel {
	switch {
	case bits < 40:
		return StrengthLow
	case bits < 75:
		return StrengthMedium
	case bits < 128:
		return StrengthHigh
	default:
		return StrengthVeryHigh
	}
}

func pluralSuffix(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
